#!/bin/sh
#Stitch complier toolchain
#Author: Dan Cole

FILENAME=`basename $1 | cut -d'.' -f1`

echo "----Stitch Compiler Toolchain----"
../ocaml/stitch $1
gcc -w ./_tests/$FILENAME.stch.c -I../runtime -L../runtime ../runtime/libstch_headers.a -o $FILENAME