#!/bin/sh
#Stich complier toolchain

FILENAME=`basename $1 | cut -d'.' -f1`

echo "----Stitch Compiler Toolchain----"
stch_compiler $1
gcc -g -Wall $FILENAME.c -L../runtime -lstch_headers -o ./$FILENAME
