#!/bin/sh
#Stich complier toolchain

FILENAME=`basename $1 | cut -d'.' -f1`

echo "----Stitch Compiler Toolchain----"
./stitch $1
gcc -w ./$FILENAME.stch.c -I../../runtime -L../../runtime ../../runtime/libstch_headers.a -o $FILENAME